image: python:3.7

stages:
  - install_dependencies
  - lint
  - test

before_script:
  - python -V             
  - pip install -r requirements.txt --quiet

lint:
  stage: lint
  script: 
    - pip install pylint pylint_runner --quiet
    - pylint_runner --rcfile=.pylintrc

test: 
  stage: test
  script: 
    - pip install pytest --quiet
    - pytest