image: python:3.7

stages:
  - lint
  - test
  - validate_models

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
# we use a virualenv to cache them
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt --quiet

lint:
  stage: lint
  script: 
    - pip install pylint pylint_runner --quiet
    - pylint_runner --rcfile=.pylintrc

test: 
  stage: test
  script: 
    - pip install pytest --quiet
    - pytest

# validate_models:
#   stage: validate_models
#   only: 
#     refs:
#       - master
#   script:
#     - git config --global user.email "gitlab@runner.com"
#     - git config --global user.name "Gitlab Runner"
#     - git remote set-url target "https://oauth2:$TOKEN@git.veios.cloud/idp1-radio/idp-radio-1.git"
#     - python3 src/tests/validate_models_script.py
#     - git add .
#     - git commit -m "Update logfile" || echo "No changes, nothing to commit!"
#     - git push target HEAD:master